[package]
name = "scpty"
authors = ["One_Ordinary_Man"]
description = "App that creates the script with shebang."
version = "0.1.1"
edition = "2021"
license = "GPL-3.0-or-later"
categories = ["command-line-utilities", "filesystem"]

[dependencies]
clap = {version="4.3.8", features=["derive"]}
